---
abstract: 'Geocode addresses with the OpenCage Geocoder API'
author:
  - 'Alex Balhatchet <alex@lokku.com>'
build_requires:
  Test::Exception: 0.32
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Coder-OpenCage
requires:
  Carp: 1.26
  HTTP::Tiny: 0.028
  JSON: 2.53
  List::MoreUtils: 0.33
  URI: 1.60
  perl: 5.008
resources:
  repository: git://github.com/lokku/perl-Geo-Coder-OpenCage.git
version: 0.03
